name: build and push Docker images

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./base/Dockerfile
            image_name: base
          - dockerfile: ./jupyter/Dockerfile
            image_name: jupyter
          - dockerfile: ./jupyter-abx/Dockerfile
            image_name: jupyter-abx
          - dockerfile: ./jupyter-abx-pyspark/Dockerfile
            image_name: jupyter-abx-pyspark

    permissions:
      contents: read
      packages: write

    steps:
      - 
        name: checkout
        uses: actions/checkout@v3
      - 
        name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ${{ matrix.dockerfile }}
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ github.event.release.tag_name }}
